create table cities
(
    id   int4 generated by default as identity,
    name varchar(100) not null,
    primary key (id));
insert into cities(name)
values ('Москва'),
       ('Сочи');

create table streets
(
    id      int4 generated by default as identity,
    name    varchar(100) not null,
    city_id int4 not null,
    foreign key (city_id) references cities(id),
    primary key (id));
insert into streets(name, city_id)
values ('Ленина',1),
       ('Южная',1),
       ('Красная',2);

create table houses
(
    id        int4 generated by default as identity,
    number    varchar(50) not null,
    street_id int4 not null,
    foreign key (street_id ) references streets(id),
    primary key (id));
insert into houses(number, street_id)
values (55,1),
       (22,2),
       (44,3);

create table apartments
(
    id       int4 generated by default as identity,
    area     float  not null,
    house_id int4 not null,
    foreign key (house_id) references  houses(id),
    primary key (id));
insert into apartments(area, house_id)
values (55,1),
       (44,2),
       (66,3);
